### PR TITLE
x1b66RTZ: Passport to support non-matching

### PR DESCRIPTION
**Pull request by alan-gds**
This covers the changes needed to make passport-verify compatible with a non-matching journey flow, but we are not happy with some of the naming.  Ideally, it would be good to rename things along the following lines, so that the non-matching journey becomes the natural default:

- createStrategy -> createMatchingStrategy
- createNonMatchingStrategy -> createStrategy
- TranslatedResponse -> TranslatedMatchingResponse
- TranslatedNonMatchingResponse -> TranslatedResponse

(personally, I'm in favour of createMatchingJourneyStrategy rather than createMatchingStrategy, but the former approach does lead to significantly longer names)

For areas of the code which are not part of the surface of the API, we have already renamed legacy (i.e. matching journey) parts and used cleaner names for the non-matching parts (or at least, that's been our aim).

### CODE REVIEW

**Comment by jakubmiarka** [comment]
I added a commit, happy to revert it back if people disagree. It should clear up some issues with the naming. Let's discuss...



I think using NonMatching in the class and implementation names
makes it confusing that the thing isn't matching, e.g. NonMatchingAddress.
I went for an "Identity" as a placeholder for non-matching stuff. 
It also makes it easier if we ever decide to remove the matching parts of the code
as we'll be only left with "Identity" which is not specific to matching/non-matching.

+ added code comments for the new code
+ updated the README accordingly with some notes on the usage.

**Comment by RacingHippo** [comment]
> I think using NonMatching in the class and implementation names
> makes it confusing that the thing isn't matching, e.g. NonMatchingAddress.
> I went for an "Identity" as a placeholder for non-matching stuff.
> It also makes it easier if we ever decide to remove the matching parts of the code
> as we'll be only left with "Identity" which is not specific to matching/non-matching.

I completely agree. We should (ideally) come at this thinking of the non-matching journey as the norm and the matching journey as the legacy exception.
"Identity" is a pretty good choice - describes what it is. 
My only concern is that someone coming to this anew wouldn't know why we had both `TranslatedResponseBody` and `TranslatedIdentityResponseBody` and what the difference was.

**Comment by alan-gds** [comment]
Is it feasible to rename TranslatedResponseBody to LegacyTranslatedResponseBody or TranslatedMsaResponsebody or something like that?  We already discussed renaming the legacy version of createStrategy() and agreed that would be an acceptable breaking change, but renaming TranslatedResponseBody would plausibly be more difficult for RPs to handle.

**Comment by RacingHippo** [comment]
Surely the class names are only visible to devs? Aren't the methods exposed to RPs the same for both journeys and routed according to VSP config?

**Comment by alan-gds** [comment]
Only to devs, yes, but what I mean is, the renaming I was proposing above would be a breaking change which would require devs on the RP side to update their client.  This would be very easy in the case of renaming createStrategy(), but I think it would be less easy/less clear to them what needed to be done in the case of renaming TranslatedResponseBody (still not massively difficult, but less easy).  It is exposed to the RP's client as it is part of the API.  https://github.com/alphagov/passport-verify/tree/master/lib/verify-service-provider-api

**Comment by jakubmiarka** [comment]
> My only concern is that someone coming to this anew wouldn't know why we had both TranslatedResponseBody and TranslatedIdentityResponseBody and what the difference was.

As @alan-gds said, the `TranslatedResponseBody` is exposed to them on the API already. I guess we could cover some of the confusion by README or something?

**Comment by RacingHippo** [comment]
We don't want to make RP's devs do _any_ work if we can possibly avoid it. It'll all end in tears... or more likely they'll just refuse to install the upgrade  :(

**Comment by jakubmiarka** [comment]
I have renamed `TranslatedResponseBody` to `TranslatedMatchingResponseBody` as we confirmed it should not have any impact on the existing users. @RacingHippo and @chrisholmes could you please review, and if happy, approve?

**Review by chrisholmes — APPROVED** [review]

**Review by RacingHippo — APPROVED** [review]

**Pull request merged**
